# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: signal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'signal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csignal.proto\x12\x06signal\"0\n\rSignalRequest\x12\r\n\x05\x61sset\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\"\x8c\x02\n\x0eSignalResponse\x12\x11\n\tid_signal\x18\x01 \x01(\t\x12\n\n\x02no\x18\x02 \x01(\x05\x12\r\n\x05\x61sset\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\t\x12\x13\n\x0btype_action\x18\x06 \x01(\t\x12\x13\n\x0btype_signal\x18\x07 \x01(\t\x12\x0b\n\x03tp1\x18\x08 \x01(\x01\x12\x0b\n\x03tp2\x18\t \x01(\x01\x12\x0b\n\x03sl1\x18\n \x01(\x01\x12\x0b\n\x03sl2\x18\x0b \x01(\x01\x12\x17\n\x0fprobability_pct\x18\x0c \x01(\x01\x12\x13\n\x0bwinrate_pct\x18\r \x01(\x01\x12\x0e\n\x06reason\x18\x0e \x01(\t\x12\x11\n\ttimestamp\x18\x0f \x01(\t2\x94\x01\n\rSignalService\x12\x41\n\x10GetTradingSignal\x12\x15.signal.SignalRequest\x1a\x16.signal.SignalResponse\x12@\n\rStreamSignals\x12\x15.signal.SignalRequest\x1a\x16.signal.SignalResponse0\x01\x42+Z)github.com/quantsync/backend/proto/signalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/quantsync/backend/proto/signal'
  _globals['_SIGNALREQUEST']._serialized_start=24
  _globals['_SIGNALREQUEST']._serialized_end=72
  _globals['_SIGNALRESPONSE']._serialized_start=75
  _globals['_SIGNALRESPONSE']._serialized_end=343
  _globals['_SIGNALSERVICE']._serialized_start=346
  _globals['_SIGNALSERVICE']._serialized_end=494
# @@protoc_insertion_point(module_scope)
