// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: signal.proto

package signal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         string                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // "crypto" or "forex"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{0}
}

func (x *SignalRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *SignalRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type SignalResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdSignal       string                 `protobuf:"bytes,1,opt,name=id_signal,json=idSignal,proto3" json:"id_signal,omitempty"`
	No             int32                  `protobuf:"varint,2,opt,name=no,proto3" json:"no,omitempty"`
	Asset          string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Price          float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Action         string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`                           // "buy" or "sell"
	TypeAction     string                 `protobuf:"bytes,6,opt,name=type_action,json=typeAction,proto3" json:"type_action,omitempty"` // "limit/stop/market/hold"
	TypeSignal     string                 `protobuf:"bytes,7,opt,name=type_signal,json=typeSignal,proto3" json:"type_signal,omitempty"` // "long" or "short"
	Tp1            float64                `protobuf:"fixed64,8,opt,name=tp1,proto3" json:"tp1,omitempty"`
	Tp2            float64                `protobuf:"fixed64,9,opt,name=tp2,proto3" json:"tp2,omitempty"`
	Sl1            float64                `protobuf:"fixed64,10,opt,name=sl1,proto3" json:"sl1,omitempty"`
	Sl2            float64                `protobuf:"fixed64,11,opt,name=sl2,proto3" json:"sl2,omitempty"`
	ProbabilityPct float64                `protobuf:"fixed64,12,opt,name=probability_pct,json=probabilityPct,proto3" json:"probability_pct,omitempty"`
	WinratePct     float64                `protobuf:"fixed64,13,opt,name=winrate_pct,json=winratePct,proto3" json:"winrate_pct,omitempty"`
	Reason         string                 `protobuf:"bytes,14,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp      string                 `protobuf:"bytes,15,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_signal_proto_rawDescGZIP(), []int{1}
}

func (x *SignalResponse) GetIdSignal() string {
	if x != nil {
		return x.IdSignal
	}
	return ""
}

func (x *SignalResponse) GetNo() int32 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *SignalResponse) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *SignalResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SignalResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SignalResponse) GetTypeAction() string {
	if x != nil {
		return x.TypeAction
	}
	return ""
}

func (x *SignalResponse) GetTypeSignal() string {
	if x != nil {
		return x.TypeSignal
	}
	return ""
}

func (x *SignalResponse) GetTp1() float64 {
	if x != nil {
		return x.Tp1
	}
	return 0
}

func (x *SignalResponse) GetTp2() float64 {
	if x != nil {
		return x.Tp2
	}
	return 0
}

func (x *SignalResponse) GetSl1() float64 {
	if x != nil {
		return x.Sl1
	}
	return 0
}

func (x *SignalResponse) GetSl2() float64 {
	if x != nil {
		return x.Sl2
	}
	return 0
}

func (x *SignalResponse) GetProbabilityPct() float64 {
	if x != nil {
		return x.ProbabilityPct
	}
	return 0
}

func (x *SignalResponse) GetWinratePct() float64 {
	if x != nil {
		return x.WinratePct
	}
	return 0
}

func (x *SignalResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SignalResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_signal_proto protoreflect.FileDescriptor

const file_signal_proto_rawDesc = "" +
	"\n" +
	"\fsignal.proto\x12\x06signal\"A\n" +
	"\rSignalRequest\x12\x14\n" +
	"\x05asset\x18\x01 \x01(\tR\x05asset\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"\x8b\x03\n" +
	"\x0eSignalResponse\x12\x1b\n" +
	"\tid_signal\x18\x01 \x01(\tR\bidSignal\x12\x0e\n" +
	"\x02no\x18\x02 \x01(\x05R\x02no\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x1f\n" +
	"\vtype_action\x18\x06 \x01(\tR\n" +
	"typeAction\x12\x1f\n" +
	"\vtype_signal\x18\a \x01(\tR\n" +
	"typeSignal\x12\x10\n" +
	"\x03tp1\x18\b \x01(\x01R\x03tp1\x12\x10\n" +
	"\x03tp2\x18\t \x01(\x01R\x03tp2\x12\x10\n" +
	"\x03sl1\x18\n" +
	" \x01(\x01R\x03sl1\x12\x10\n" +
	"\x03sl2\x18\v \x01(\x01R\x03sl2\x12'\n" +
	"\x0fprobability_pct\x18\f \x01(\x01R\x0eprobabilityPct\x12\x1f\n" +
	"\vwinrate_pct\x18\r \x01(\x01R\n" +
	"winratePct\x12\x16\n" +
	"\x06reason\x18\x0e \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\x0f \x01(\tR\ttimestamp2\x94\x01\n" +
	"\rSignalService\x12A\n" +
	"\x10GetTradingSignal\x12\x15.signal.SignalRequest\x1a\x16.signal.SignalResponse\x12@\n" +
	"\rStreamSignals\x12\x15.signal.SignalRequest\x1a\x16.signal.SignalResponse0\x01B5Z3github.com/quantsync/quantsync-gateway/proto/signalb\x06proto3"

var (
	file_signal_proto_rawDescOnce sync.Once
	file_signal_proto_rawDescData []byte
)

func file_signal_proto_rawDescGZIP() []byte {
	file_signal_proto_rawDescOnce.Do(func() {
		file_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signal_proto_rawDesc), len(file_signal_proto_rawDesc)))
	})
	return file_signal_proto_rawDescData
}

var file_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_signal_proto_goTypes = []any{
	(*SignalRequest)(nil),  // 0: signal.SignalRequest
	(*SignalResponse)(nil), // 1: signal.SignalResponse
}
var file_signal_proto_depIdxs = []int32{
	0, // 0: signal.SignalService.GetTradingSignal:input_type -> signal.SignalRequest
	0, // 1: signal.SignalService.StreamSignals:input_type -> signal.SignalRequest
	1, // 2: signal.SignalService.GetTradingSignal:output_type -> signal.SignalResponse
	1, // 3: signal.SignalService.StreamSignals:output_type -> signal.SignalResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_signal_proto_init() }
func file_signal_proto_init() {
	if File_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signal_proto_rawDesc), len(file_signal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signal_proto_goTypes,
		DependencyIndexes: file_signal_proto_depIdxs,
		MessageInfos:      file_signal_proto_msgTypes,
	}.Build()
	File_signal_proto = out.File
	file_signal_proto_goTypes = nil
	file_signal_proto_depIdxs = nil
}
