// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: signal.proto

package signal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignalService_GetTradingSignal_FullMethodName = "/signal.SignalService/GetTradingSignal"
	SignalService_StreamSignals_FullMethodName    = "/signal.SignalService/StreamSignals"
)

// SignalServiceClient is the client API for SignalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignalServiceClient interface {
	GetTradingSignal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	StreamSignals(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignalResponse], error)
}

type signalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignalServiceClient(cc grpc.ClientConnInterface) SignalServiceClient {
	return &signalServiceClient{cc}
}

func (c *signalServiceClient) GetTradingSignal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, SignalService_GetTradingSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalServiceClient) StreamSignals(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignalResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SignalService_ServiceDesc.Streams[0], SignalService_StreamSignals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SignalRequest, SignalResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignalService_StreamSignalsClient = grpc.ServerStreamingClient[SignalResponse]

// SignalServiceServer is the server API for SignalService service.
// All implementations must embed UnimplementedSignalServiceServer
// for forward compatibility.
type SignalServiceServer interface {
	GetTradingSignal(context.Context, *SignalRequest) (*SignalResponse, error)
	StreamSignals(*SignalRequest, grpc.ServerStreamingServer[SignalResponse]) error
	mustEmbedUnimplementedSignalServiceServer()
}

// UnimplementedSignalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignalServiceServer struct{}

func (UnimplementedSignalServiceServer) GetTradingSignal(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTradingSignal not implemented")
}
func (UnimplementedSignalServiceServer) StreamSignals(*SignalRequest, grpc.ServerStreamingServer[SignalResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamSignals not implemented")
}
func (UnimplementedSignalServiceServer) mustEmbedUnimplementedSignalServiceServer() {}
func (UnimplementedSignalServiceServer) testEmbeddedByValue()                       {}

// UnsafeSignalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignalServiceServer will
// result in compilation errors.
type UnsafeSignalServiceServer interface {
	mustEmbedUnimplementedSignalServiceServer()
}

func RegisterSignalServiceServer(s grpc.ServiceRegistrar, srv SignalServiceServer) {
	// If the following call panics, it indicates UnimplementedSignalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignalService_ServiceDesc, srv)
}

func _SignalService_GetTradingSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalServiceServer).GetTradingSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignalService_GetTradingSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalServiceServer).GetTradingSignal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignalService_StreamSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SignalRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SignalServiceServer).StreamSignals(m, &grpc.GenericServerStream[SignalRequest, SignalResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignalService_StreamSignalsServer = grpc.ServerStreamingServer[SignalResponse]

// SignalService_ServiceDesc is the grpc.ServiceDesc for SignalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signal.SignalService",
	HandlerType: (*SignalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTradingSignal",
			Handler:    _SignalService_GetTradingSignal_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSignals",
			Handler:       _SignalService_StreamSignals_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "signal.proto",
}
